//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EindopdrachtProg6.ValutaReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ValutaReference.IValutaConverter")]
    public interface IValutaConverter {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaConverter/ConvertToJPY", ReplyAction="http://tempuri.org/IValutaConverter/ConvertToJPYResponse")]
        decimal ConvertToJPY(decimal euro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaConverter/ConvertToJPY", ReplyAction="http://tempuri.org/IValutaConverter/ConvertToJPYResponse")]
        System.Threading.Tasks.Task<decimal> ConvertToJPYAsync(decimal euro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaConverter/ConvertToUSD", ReplyAction="http://tempuri.org/IValutaConverter/ConvertToUSDResponse")]
        decimal ConvertToUSD(decimal euro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IValutaConverter/ConvertToUSD", ReplyAction="http://tempuri.org/IValutaConverter/ConvertToUSDResponse")]
        System.Threading.Tasks.Task<decimal> ConvertToUSDAsync(decimal euro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IValutaConverterChannel : EindopdrachtProg6.ValutaReference.IValutaConverter, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValutaConverterClient : System.ServiceModel.ClientBase<EindopdrachtProg6.ValutaReference.IValutaConverter>, EindopdrachtProg6.ValutaReference.IValutaConverter {
        
        public ValutaConverterClient() {
        }
        
        public ValutaConverterClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValutaConverterClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValutaConverterClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValutaConverterClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public decimal ConvertToJPY(decimal euro) {
            return base.Channel.ConvertToJPY(euro);
        }
        
        public System.Threading.Tasks.Task<decimal> ConvertToJPYAsync(decimal euro) {
            return base.Channel.ConvertToJPYAsync(euro);
        }
        
        public decimal ConvertToUSD(decimal euro) {
            return base.Channel.ConvertToUSD(euro);
        }
        
        public System.Threading.Tasks.Task<decimal> ConvertToUSDAsync(decimal euro) {
            return base.Channel.ConvertToUSDAsync(euro);
        }
    }
}
